commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta2

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackfailuredomains.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackisolatednetworks.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackzones.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackaffinitygroups.yaml
- bases/infrastructure.cluster.x-k8s.io_cloudstackmachinestatecheckers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_cloudstackclusters.yaml
- patches/webhook_in_cloudstackmachines.yaml
- patches/webhook_in_cloudstackmachinetemplates.yaml
- patches/webhook_in_cloudstackisolatednetworks.yaml
# - patches/webhook_in_cloudstackzones.yaml
- patches/webhook_in_cloudstackaffinitygroups.yaml
- patches/webhook_in_cloudstackmachinestatecheckers.yaml
# - patches/webhook_in_cloudstackfailuredomains.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_cloudstackclusters.yaml
- patches/cainjection_in_cloudstackmachines.yaml
- patches/cainjection_in_cloudstackmachinetemplates.yaml
- patches/cainjection_in_cloudstackisolatednetworks.yaml
- patches/cainjection_in_cloudstackzones.yaml
- patches/cainjection_in_cloudstackaffinitygroups.yaml
- patches/cainjection_in_cloudstackmachinestatecheckers.yaml
- patches/cainjection_in_cloudstackfailuredomains.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
